/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

/**
 *
 * @author User
 */
public class deshboardPanel extends javax.swing.JPanel {

    /**
     * Creates new form deshboardPanel
     */
    public deshboardPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tablePanel = new javax.swing.JPanel();
        lowStockPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLowStock = new javax.swing.JTable();
        recentMovmentsPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblRecentMovements = new javax.swing.JTable();
        deshboardHeaderPanel = new javax.swing.JPanel();
        namePanelLabel = new javax.swing.JLabel();
        dashboaedDateLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));
        setForeground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        tablePanel.setBackground(new java.awt.Color(51, 51, 51));
        tablePanel.setForeground(new java.awt.Color(51, 51, 51));
        tablePanel.setName("tablesContainer"); // NOI18N
        tablePanel.setLayout(new java.awt.GridLayout(2, 1, 10, 10));

        lowStockPanel.setBackground(new java.awt.Color(51, 51, 51));
        lowStockPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ТОВАРЫ С НИЗКИМ ОСТАТКОМ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        lowStockPanel.setForeground(new java.awt.Color(51, 51, 51));
        lowStockPanel.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setForeground(new java.awt.Color(51, 51, 51));
        jScrollPane1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        tblLowStock.setBackground(new java.awt.Color(255, 255, 255));
        tblLowStock.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tblLowStock.setForeground(new java.awt.Color(51, 51, 51));
        tblLowStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblLowStock.setName("tblLowStock"); // NOI18N
        tblLowStock.setSelectionForeground(new java.awt.Color(51, 51, 51));
        jScrollPane1.setViewportView(tblLowStock);

        lowStockPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        tablePanel.add(lowStockPanel);

        recentMovmentsPanel.setBackground(new java.awt.Color(51, 51, 51));
        recentMovmentsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ПОСЛЕДНИЕ ОПЕРАЦИИ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        recentMovmentsPanel.setForeground(new java.awt.Color(51, 51, 51));
        recentMovmentsPanel.setLayout(new java.awt.BorderLayout());

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setForeground(new java.awt.Color(51, 51, 51));
        jScrollPane2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        tblRecentMovements.setBackground(new java.awt.Color(255, 255, 255));
        tblRecentMovements.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tblRecentMovements.setForeground(new java.awt.Color(51, 51, 51));
        tblRecentMovements.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblRecentMovements.setName("tblRecentMovements"); // NOI18N
        tblRecentMovements.setSelectionForeground(new java.awt.Color(51, 51, 51));
        jScrollPane2.setViewportView(tblRecentMovements);

        recentMovmentsPanel.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        tablePanel.add(recentMovmentsPanel);

        add(tablePanel, java.awt.BorderLayout.CENTER);

        deshboardHeaderPanel.setBackground(new java.awt.Color(51, 51, 51));
        deshboardHeaderPanel.setLayout(new java.awt.GridBagLayout());

        namePanelLabel.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        namePanelLabel.setForeground(new java.awt.Color(255, 255, 255));
        namePanelLabel.setText("Панель управления");
        namePanelLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        deshboardHeaderPanel.add(namePanelLabel, new java.awt.GridBagConstraints());

        dashboaedDateLabel.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        dashboaedDateLabel.setForeground(new java.awt.Color(255, 255, 255));
        dashboaedDateLabel.setText("время");
        dashboaedDateLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        deshboardHeaderPanel.add(dashboaedDateLabel, new java.awt.GridBagConstraints());

        add(deshboardHeaderPanel, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dashboaedDateLabel;
    private javax.swing.JPanel deshboardHeaderPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel lowStockPanel;
    private javax.swing.JLabel namePanelLabel;
    private javax.swing.JPanel recentMovmentsPanel;
    private javax.swing.JPanel tablePanel;
    private javax.swing.JTable tblLowStock;
    private javax.swing.JTable tblRecentMovements;
    // End of variables declaration//GEN-END:variables
}
