/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import controllers.Controller;
import dao.UserDAO;
import model.User;

import javax.swing.*;
import java.time.LocalDateTime;

/**
 *
 * @author User
 */
public class LoginFormNET extends javax.swing.JFrame {


    /**
     * Creates new form LoginFormNET
     */
    public LoginFormNET() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        backgroundPanel = new javax.swing.JPanel();
        componentPanel = new javax.swing.JPanel();
        titleLable = new javax.swing.JLabel();
        descriptionLabel = new javax.swing.JLabel();
        loginLabel = new javax.swing.JLabel();
        loginField = new javax.swing.JTextField();
        enterButton = new javax.swing.JButton();
        versionLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WarehouseIS");
        setBackground(new java.awt.Color(44, 62, 80));
        setName("LoginForm"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));

        backgroundPanel.setBackground(new java.awt.Color(33, 37, 41));
        backgroundPanel.setPreferredSize(new java.awt.Dimension(800, 600));
        backgroundPanel.setLayout(new java.awt.GridBagLayout());

        componentPanel.setBackground(new java.awt.Color(51, 51, 51));
        componentPanel.setForeground(new java.awt.Color(51, 51, 51));
        componentPanel.setPreferredSize(new java.awt.Dimension(400, 500));
        componentPanel.setLayout(new java.awt.GridBagLayout());

        titleLable.setBackground(new java.awt.Color(44, 62, 80));
        titleLable.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        titleLable.setForeground(new java.awt.Color(255, 255, 255));
        titleLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLable.setText("WarehouseIS");
        titleLable.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(40, 0, 5, 0);
        componentPanel.add(titleLable, gridBagConstraints);

        descriptionLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        descriptionLabel.setForeground(new java.awt.Color(204, 204, 204));
        descriptionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        descriptionLabel.setText("Управление складом");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 30, 0);
        componentPanel.add(descriptionLabel, gridBagConstraints);

        loginLabel.setBackground(new java.awt.Color(52, 73, 94));
        loginLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        loginLabel.setForeground(new java.awt.Color(204, 204, 204));
        loginLabel.setText("Логин");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        componentPanel.add(loginLabel, gridBagConstraints);

        loginField.setColumns(20);
        loginField.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(189, 195, 199)), javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10)));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 15, 0);
        componentPanel.add(loginField, gridBagConstraints);

        enterButton.setBackground(new java.awt.Color(52, 152, 219));
        enterButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        enterButton.setForeground(new java.awt.Color(255, 255, 255));
        enterButton.setText("Войти");
        enterButton.setBorderPainted(false);
        enterButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        enterButton.setFocusPainted(false);
        enterButton.setPreferredSize(new java.awt.Dimension(320, 45));
        enterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 15, 0);
        componentPanel.add(enterButton, gridBagConstraints);

        versionLabel.setBackground(new java.awt.Color(189, 195, 199));
        versionLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        versionLabel.setForeground(new java.awt.Color(189, 195, 199));
        versionLabel.setText("Версия 1.0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 30, 0);
        componentPanel.add(versionLabel, gridBagConstraints);

        passwordLabel.setBackground(new java.awt.Color(52, 73, 94));
        passwordLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(204, 204, 204));
        passwordLabel.setText("Пароль");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        componentPanel.add(passwordLabel, gridBagConstraints);

        passwordField.setColumns(20);
        passwordField.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(189, 195, 199)), javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10)));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        componentPanel.add(passwordField, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        backgroundPanel.add(componentPanel, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void enterButtonActionPerformed(java.awt.event.ActionEvent evt) {
        Controller con = new Controller();
        UserDAO userDAO = new UserDAO();
        String login = loginField.getText().trim();
        String password = passwordField.getText().trim();


        if (!con.checkAccept(login, password)) {
            JOptionPane.showMessageDialog(this, "Заполните все поля.", "Предупреждение", JOptionPane.WARNING_MESSAGE);
            return;
        }

        User user = userDAO.getUserInDb(login);


        if (user == null) {
            JOptionPane.showMessageDialog(this, "Пользователь с таким логином не найден", "Ошибка", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (user.getIsBlocked()) {
            JOptionPane.showMessageDialog(this, "Ваш пользователь был заблокирован, обратитесь к администратору", "Внимание", JOptionPane.WARNING_MESSAGE);
            clearFields();
            return;
        }

        if (!user.getPassword().equals(password)) {
            user.incrementFailedAttempts();
            userDAO.updateUser(user);

            JOptionPane.showMessageDialog(this, "Вы ввели неправильный логин или пароль", "Внимание", JOptionPane.WARNING_MESSAGE);
            return;
        }

        LocalDateTime ldt = LocalDateTime.now();
        user.setLastLogin(ldt);
        user.resetFailedAttempts();
        userDAO.updateUser(user);

        if (user.isMustChangePassword()) {
            JOptionPane.showMessageDialog(this, "Вам был выдан временный пароль, пожалуйста поменяйте его", "Внимание", JOptionPane.WARNING_MESSAGE);
        }

        JOptionPane.showMessageDialog(this, "Добро пожаловать " + user.getFullName(), "Успех", JOptionPane.INFORMATION_MESSAGE);

        MainForm mainForm = new MainForm(this, user);
        mainForm.setVisible(true);
        this.setVisible(false);
        clearFields();
    }

    private void clearFields() {
        loginField.setText("");
        passwordField.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFormNET.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFormNET.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFormNET.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFormNET.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFormNET().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JPanel componentPanel;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JButton enterButton;
    private javax.swing.JTextField loginField;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel titleLable;
    private javax.swing.JLabel versionLabel;
    // End of variables declaration//GEN-END:variables
}