/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import View.Panels.productsPanel;
import View.Panels.deshboardPanel;
import View.Panels.settingsPanel;
import View.Panels.usersPanel;
import View.Panels.OutcomePanel;
import View.Panels.WarehousesPanel;
import View.Panels.IncomePanel;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author User
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    private JFrame parrentFrame;
    private CardLayout cardLayout;
    private deshboardPanel dashboardPanel;
    private settingsPanel settingsPanel;
    private productsPanel productPanel;
    private WarehousesPanel warehousePanel;
    private IncomePanel incomePanel;
    private OutcomePanel outcomePanel;
    private usersPanel userPanel;
    private boolean isAdmin = false;

    public MainForm(JFrame parrentFrame) {
        this.parrentFrame = parrentFrame;
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();

        contentPanel.removeAll();
        contentPanel.setLayout(new CardLayout());
        cardLayout = (CardLayout) contentPanel.getLayout();

        dashboardPanel = new deshboardPanel();
        settingsPanel = new settingsPanel();
        productPanel = new productsPanel();
        warehousePanel = new WarehousesPanel();
        incomePanel = new IncomePanel();
        outcomePanel = new OutcomePanel();
        userPanel = new usersPanel();

        contentPanel.add(dashboardPanel, "dashboard");
        contentPanel.add(settingsPanel, "settings");
        contentPanel.add(productPanel, "products");
        contentPanel.add(warehousePanel, "warehouses");
        contentPanel.add(incomePanel, "income");
        contentPanel.add(outcomePanel, "outcome");
        contentPanel.add(userPanel, "users");

        cardLayout.show(contentPanel, "dashboard");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        sidebarPanel = new javax.swing.JPanel();
        dashboardButton = new javax.swing.JButton();
        productButton = new javax.swing.JButton();
        warehouseButton = new javax.swing.JButton();
        comingButton = new javax.swing.JButton();
        expenditureButton = new javax.swing.JButton();
        usersButton = new javax.swing.JButton();
        settingsButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setName("mainForm"); // NOI18N
        setSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(null);

        headerPanel.setBackground(new java.awt.Color(33, 37, 41));
        headerPanel.setName("headerPanel"); // NOI18N
        headerPanel.setPreferredSize(new java.awt.Dimension(1200, 50));
        headerPanel.setLayout(new java.awt.BorderLayout());

        headerLabel.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        headerLabel.setForeground(new java.awt.Color(255, 255, 255));
        headerLabel.setText("WarehouseIS");
        headerPanel.add(headerLabel, java.awt.BorderLayout.LINE_START);

        userLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        userLabel.setForeground(new java.awt.Color(255, 255, 255));
        userLabel.setText("Имя пользователя");
        userLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        headerPanel.add(userLabel, java.awt.BorderLayout.LINE_END);

        getContentPane().add(headerPanel);
        headerPanel.setBounds(0, 0, 1920, 50);

        mainPanel.setLayout(new java.awt.BorderLayout());

        sidebarPanel.setBackground(new java.awt.Color(33, 37, 41));
        sidebarPanel.setPreferredSize(new java.awt.Dimension(220, 640));
        sidebarPanel.setLayout(new javax.swing.BoxLayout(sidebarPanel, javax.swing.BoxLayout.PAGE_AXIS));

        dashboardButton.setBackground(new java.awt.Color(52, 152, 219));
        dashboardButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        dashboardButton.setForeground(new java.awt.Color(255, 255, 255));
        dashboardButton.setText("Понель управления");
        dashboardButton.setFocusPainted(false);
        dashboardButton.setMaximumSize(new java.awt.Dimension(200, 40));
        dashboardButton.setPreferredSize(new java.awt.Dimension(85, 24));
        dashboardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardButtonActionPerformed(evt);
            }
        });
        sidebarPanel.add(dashboardButton);

        productButton.setBackground(new java.awt.Color(52, 152, 219));
        productButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        productButton.setForeground(new java.awt.Color(255, 255, 255));
        productButton.setText("Товары");
        productButton.setFocusPainted(false);
        productButton.setMaximumSize(new java.awt.Dimension(200, 40));
        productButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productButtonActionPerformed(evt);
            }
        });
        sidebarPanel.add(productButton);

        warehouseButton.setBackground(new java.awt.Color(52, 152, 219));
        warehouseButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        warehouseButton.setForeground(new java.awt.Color(255, 255, 255));
        warehouseButton.setText("Склады");
        warehouseButton.setFocusPainted(false);
        warehouseButton.setMaximumSize(new java.awt.Dimension(200, 40));
        warehouseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                warehouseButtonActionPerformed(evt);
            }
        });
        sidebarPanel.add(warehouseButton);

        comingButton.setBackground(new java.awt.Color(52, 152, 219));
        comingButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        comingButton.setForeground(new java.awt.Color(255, 255, 255));
        comingButton.setText("Приход");
        comingButton.setFocusPainted(false);
        comingButton.setMaximumSize(new java.awt.Dimension(200, 40));
        comingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comingButtonActionPerformed(evt);
            }
        });
        sidebarPanel.add(comingButton);

        expenditureButton.setBackground(new java.awt.Color(52, 152, 219));
        expenditureButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        expenditureButton.setForeground(new java.awt.Color(255, 255, 255));
        expenditureButton.setText("Расход");
        expenditureButton.setFocusPainted(false);
        expenditureButton.setMaximumSize(new java.awt.Dimension(200, 40));
        expenditureButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expenditureButtonActionPerformed(evt);
            }
        });
        sidebarPanel.add(expenditureButton);

        usersButton.setBackground(new java.awt.Color(52, 152, 219));
        usersButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        usersButton.setForeground(new java.awt.Color(255, 255, 255));
        usersButton.setText("Пользователи");
        usersButton.setFocusPainted(false);
        usersButton.setMaximumSize(new java.awt.Dimension(200, 40));
        usersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usersButtonActionPerformed(evt);
            }
        });
        sidebarPanel.add(usersButton);

        settingsButton.setBackground(new java.awt.Color(52, 152, 219));
        settingsButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        settingsButton.setForeground(new java.awt.Color(255, 255, 255));
        settingsButton.setText("Настройки");
        settingsButton.setFocusPainted(false);
        settingsButton.setMaximumSize(new java.awt.Dimension(200, 40));
        settingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsButtonActionPerformed(evt);
            }
        });
        sidebarPanel.add(settingsButton);

        exitButton.setBackground(new java.awt.Color(52, 152, 219));
        exitButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        exitButton.setForeground(new java.awt.Color(255, 255, 255));
        exitButton.setText("Выход");
        exitButton.setFocusPainted(false);
        exitButton.setMaximumSize(new java.awt.Dimension(200, 40));
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        sidebarPanel.add(exitButton);

        mainPanel.add(sidebarPanel, java.awt.BorderLayout.LINE_START);

        contentPanel.setBackground(new java.awt.Color(33, 37, 41));
        contentPanel.setLayout(new java.awt.CardLayout());
        mainPanel.add(contentPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(mainPanel);
        mainPanel.setBounds(0, 50, 1920, 1030);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dashboardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardButtonActionPerformed
        cardLayout.show(contentPanel, "dashboard");
    }//GEN-LAST:event_dashboardButtonActionPerformed

    private void productButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productButtonActionPerformed
        cardLayout.show(contentPanel, "products");
    }//GEN-LAST:event_productButtonActionPerformed

    private void warehouseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_warehouseButtonActionPerformed
        cardLayout.show(contentPanel, "warehouses");
    }//GEN-LAST:event_warehouseButtonActionPerformed

    private void comingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comingButtonActionPerformed
        cardLayout.show(contentPanel, "income");
    }//GEN-LAST:event_comingButtonActionPerformed

    private void expenditureButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expenditureButtonActionPerformed
        cardLayout.show(contentPanel, "outcome");
    }//GEN-LAST:event_expenditureButtonActionPerformed

    private void usersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usersButtonActionPerformed
        cardLayout.show(contentPanel, "users");
    }//GEN-LAST:event_usersButtonActionPerformed

    private void settingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsButtonActionPerformed
        cardLayout.show(contentPanel, "settings");
    }//GEN-LAST:event_settingsButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        parrentFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton comingButton;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JButton dashboardButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton expenditureButton;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton productButton;
    private javax.swing.JButton settingsButton;
    private javax.swing.JPanel sidebarPanel;
    private javax.swing.JLabel userLabel;
    private javax.swing.JButton usersButton;
    private javax.swing.JButton warehouseButton;
    // End of variables declaration//GEN-END:variables
}
