/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

/**
 *
 * @author User
 */
public class WarehousesPanel extends javax.swing.JPanel {

    /**
     * Creates new form WarehousesPanel
     */
    public WarehousesPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        warehouseHeaderPanel = new javax.swing.JPanel();
        namePanelLabel = new javax.swing.JLabel();
        productDateLabel = new javax.swing.JLabel();
        buttonPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        tablePanel = new javax.swing.JPanel();
        tableScrollPane = new javax.swing.JScrollPane();
        tblWarehouse = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        warehouseHeaderPanel.setBackground(new java.awt.Color(51, 51, 51));
        warehouseHeaderPanel.setLayout(new java.awt.GridBagLayout());

        namePanelLabel.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        namePanelLabel.setForeground(new java.awt.Color(255, 255, 255));
        namePanelLabel.setText("Управление складами");
        namePanelLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        warehouseHeaderPanel.add(namePanelLabel, new java.awt.GridBagConstraints());

        productDateLabel.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        productDateLabel.setForeground(new java.awt.Color(255, 255, 255));
        productDateLabel.setText("время");
        productDateLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        warehouseHeaderPanel.add(productDateLabel, new java.awt.GridBagConstraints());

        add(warehouseHeaderPanel, java.awt.BorderLayout.PAGE_START);

        buttonPanel.setMaximumSize(new java.awt.Dimension(900, 35));
        buttonPanel.setMinimumSize(new java.awt.Dimension(900, 35));
        buttonPanel.setPreferredSize(new java.awt.Dimension(900, 35));

        jButton1.setBackground(new java.awt.Color(40, 167, 69));
        jButton1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Добавить");
        jButton1.setFocusPainted(false);
        jButton1.setPreferredSize(new java.awt.Dimension(130, 35));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        buttonPanel.add(jButton1);

        jButton2.setBackground(new java.awt.Color(255, 193, 7));
        jButton2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Редактировать");
        jButton2.setFocusPainted(false);
        jButton2.setMaximumSize(new java.awt.Dimension(190, 29));
        jButton2.setPreferredSize(new java.awt.Dimension(170, 35));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        buttonPanel.add(jButton2);

        jButton3.setBackground(new java.awt.Color(220, 53, 69));
        jButton3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Удалить");
        jButton3.setFocusPainted(false);
        jButton3.setPreferredSize(new java.awt.Dimension(130, 35));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        buttonPanel.add(jButton3);

        jButton5.setBackground(new java.awt.Color(255, 153, 0));
        jButton5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Обновить");
        jButton5.setFocusPainted(false);
        jButton5.setPreferredSize(new java.awt.Dimension(130, 35));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        buttonPanel.add(jButton5);

        add(buttonPanel, java.awt.BorderLayout.CENTER);

        tablePanel.setPreferredSize(new java.awt.Dimension(900, 900));
        tablePanel.setLayout(new java.awt.BorderLayout());

        tableScrollPane.setPreferredSize(new java.awt.Dimension(900, 700));

        tblWarehouse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblWarehouse.setRowHeight(30);
        tableScrollPane.setViewportView(tblWarehouse);

        tablePanel.add(tableScrollPane, java.awt.BorderLayout.CENTER);

        add(tablePanel, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel namePanelLabel;
    private javax.swing.JLabel productDateLabel;
    private javax.swing.JPanel tablePanel;
    private javax.swing.JScrollPane tableScrollPane;
    private javax.swing.JTable tblWarehouse;
    private javax.swing.JPanel warehouseHeaderPanel;
    // End of variables declaration//GEN-END:variables
}
