/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.example.View;

import javax.swing.*;

/**
 *
 * @author User
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        setupTables();
        loadTestData();
    }
    
    private void setupTables() {
    // Таблица 1: Низкий остаток
    tblLowStock.setModel(new javax.swing.table.DefaultTableModel(
        new Object[][]{},
        new String[]{"SKU", "Товар", "Остаток", "Мин."}
    ));
    tblLowStock.setRowHeight(30);
    
    // Таблица 2: Последние операции
    tblRecentMovements.setModel(new javax.swing.table.DefaultTableModel(
        new Object[][]{},
        new String[]{"Дата", "Тип", "Товар", "Кол-во", "Кто"}
    ));
    tblRecentMovements.setRowHeight(30);
}

private void loadTestData() {
    // Заполняем первую таблицу
    javax.swing.table.DefaultTableModel lowModel = 
        (javax.swing.table.DefaultTableModel) tblLowStock.getModel();
    
    lowModel.addRow(new Object[]{"NB-001", "Ноутбук Lenovo", "3", "5"});
    lowModel.addRow(new Object[]{"DR-002", "Дрель Makita", "7", "10"});
    lowModel.addRow(new Object[]{"MN-003", "Монитор Samsung", "2", "3"});
    
    // Заполняем вторую таблицу
    javax.swing.table.DefaultTableModel recentModel = 
        (javax.swing.table.DefaultTableModel) tblRecentMovements.getModel();
    
    recentModel.addRow(new Object[]{"07.06 14:30", "IN", "Ноутбук Lenovo", "+10", "Иван"});
    recentModel.addRow(new Object[]{"07.06 11:20", "OUT", "Дрель Makita", "-3", "Пётр"});
    recentModel.addRow(new Object[]{"06.06 16:45", "IN", "Монитор Samsung", "+5", "Иван"});
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        sidebarPanel = new javax.swing.JPanel();
        dashboardButton = new javax.swing.JButton();
        productButton = new javax.swing.JButton();
        warehouseButton = new javax.swing.JButton();
        comingButton = new javax.swing.JButton();
        expenditureButton = new javax.swing.JButton();
        historyButton = new javax.swing.JButton();
        usersButton = new javax.swing.JButton();
        settingsButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();
        namePanelLabel = new javax.swing.JLabel();
        tablesPanel = new javax.swing.JPanel();
        lowStockContainer = new javax.swing.JPanel();
        lowStockScrollPane = new javax.swing.JScrollPane();
        tblLowStock = new javax.swing.JTable();
        recentContainer = new javax.swing.JPanel();
        recentScrollPane = new javax.swing.JScrollPane();
        tblRecentMovements = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WarehouseIS - Панель управления");
        setMaximumSize(null);
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setName("dashboard"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        setResizable(false);
        setSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(null);

        headerPanel.setBackground(new java.awt.Color(33, 37, 41));
        headerPanel.setName("headerPanel"); // NOI18N
        headerPanel.setPreferredSize(new java.awt.Dimension(1200, 50));
        headerPanel.setLayout(new java.awt.BorderLayout());

        headerLabel.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        headerLabel.setForeground(new java.awt.Color(255, 255, 255));
        headerLabel.setText("WarehouseIS");
        headerPanel.add(headerLabel, java.awt.BorderLayout.LINE_START);

        userLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        userLabel.setForeground(new java.awt.Color(255, 255, 255));
        userLabel.setText("Имя пользователя");
        headerPanel.add(userLabel, java.awt.BorderLayout.LINE_END);

        getContentPane().add(headerPanel);
        headerPanel.setBounds(0, 0, 1920, 50);

        mainPanel.setLayout(new java.awt.BorderLayout());

        sidebarPanel.setBackground(new java.awt.Color(33, 37, 41));
        sidebarPanel.setPreferredSize(new java.awt.Dimension(220, 640));
        sidebarPanel.setLayout(new javax.swing.BoxLayout(sidebarPanel, javax.swing.BoxLayout.PAGE_AXIS));

        dashboardButton.setBackground(new java.awt.Color(52, 152, 219));
        dashboardButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        dashboardButton.setForeground(new java.awt.Color(255, 255, 255));
        dashboardButton.setText("ДАШБОРД");
        dashboardButton.setFocusPainted(false);
        dashboardButton.setMaximumSize(new java.awt.Dimension(200, 40));
        sidebarPanel.add(dashboardButton);

        productButton.setBackground(new java.awt.Color(52, 152, 219));
        productButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        productButton.setForeground(new java.awt.Color(255, 255, 255));
        productButton.setText("Товары");
        productButton.setFocusPainted(false);
        productButton.setMaximumSize(new java.awt.Dimension(200, 40));
        sidebarPanel.add(productButton);

        warehouseButton.setBackground(new java.awt.Color(52, 152, 219));
        warehouseButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        warehouseButton.setForeground(new java.awt.Color(255, 255, 255));
        warehouseButton.setText("Склады");
        warehouseButton.setFocusPainted(false);
        warehouseButton.setMaximumSize(new java.awt.Dimension(200, 40));
        sidebarPanel.add(warehouseButton);

        comingButton.setBackground(new java.awt.Color(52, 152, 219));
        comingButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        comingButton.setForeground(new java.awt.Color(255, 255, 255));
        comingButton.setText("Приход");
        comingButton.setFocusPainted(false);
        comingButton.setMaximumSize(new java.awt.Dimension(200, 40));
        sidebarPanel.add(comingButton);

        expenditureButton.setBackground(new java.awt.Color(52, 152, 219));
        expenditureButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        expenditureButton.setForeground(new java.awt.Color(255, 255, 255));
        expenditureButton.setText("Расход");
        expenditureButton.setFocusPainted(false);
        expenditureButton.setMaximumSize(new java.awt.Dimension(200, 40));
        sidebarPanel.add(expenditureButton);

        historyButton.setBackground(new java.awt.Color(52, 152, 219));
        historyButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        historyButton.setForeground(new java.awt.Color(255, 255, 255));
        historyButton.setText("История");
        historyButton.setFocusPainted(false);
        historyButton.setMaximumSize(new java.awt.Dimension(200, 40));
        sidebarPanel.add(historyButton);

        usersButton.setBackground(new java.awt.Color(52, 152, 219));
        usersButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        usersButton.setForeground(new java.awt.Color(255, 255, 255));
        usersButton.setText("Пользователи");
        usersButton.setFocusPainted(false);
        usersButton.setMaximumSize(new java.awt.Dimension(200, 40));
        sidebarPanel.add(usersButton);

        settingsButton.setBackground(new java.awt.Color(52, 152, 219));
        settingsButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        settingsButton.setForeground(new java.awt.Color(255, 255, 255));
        settingsButton.setText("Настройки");
        settingsButton.setFocusPainted(false);
        settingsButton.setMaximumSize(new java.awt.Dimension(200, 40));
        sidebarPanel.add(settingsButton);

        exitButton.setBackground(new java.awt.Color(52, 152, 219));
        exitButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        exitButton.setForeground(new java.awt.Color(255, 255, 255));
        exitButton.setText("Выход");
        exitButton.setFocusPainted(false);
        exitButton.setMaximumSize(new java.awt.Dimension(200, 40));
        sidebarPanel.add(exitButton);

        mainPanel.add(sidebarPanel, java.awt.BorderLayout.LINE_START);

        contentPanel.setBackground(new java.awt.Color(255, 255, 255));
        contentPanel.setLayout(new java.awt.BorderLayout());

        namePanelLabel.setBackground(new java.awt.Color(0, 0, 0));
        namePanelLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        namePanelLabel.setForeground(new java.awt.Color(0, 0, 0));
        namePanelLabel.setText("Панель управления");
        namePanelLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 10, 20));
        contentPanel.add(namePanelLabel, java.awt.BorderLayout.PAGE_START);

        tablesPanel.setBackground(new java.awt.Color(255, 255, 255));
        tablesPanel.setLayout(new java.awt.GridLayout(2, 1, 10, 10));

        lowStockContainer.setBackground(new java.awt.Color(255, 255, 255));
        lowStockContainer.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ТОВАРЫ С НИЗКИМ ОСТАТКОМ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18), new java.awt.Color(0, 0, 0))); // NOI18N
        lowStockContainer.setLayout(new java.awt.BorderLayout());

        lowStockScrollPane.setBackground(new java.awt.Color(255, 255, 255));
        lowStockScrollPane.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        tblLowStock.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tblLowStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        lowStockScrollPane.setViewportView(tblLowStock);

        lowStockContainer.add(lowStockScrollPane, java.awt.BorderLayout.CENTER);

        tablesPanel.add(lowStockContainer);

        recentContainer.setBackground(new java.awt.Color(255, 255, 255));
        recentContainer.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ПОСЛЕДНИЕ ОПЕРАЦИИ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18), new java.awt.Color(0, 0, 0))); // NOI18N
        recentContainer.setLayout(new java.awt.BorderLayout());

        tblRecentMovements.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tblRecentMovements.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        recentScrollPane.setViewportView(tblRecentMovements);

        recentContainer.add(recentScrollPane, java.awt.BorderLayout.CENTER);

        tablesPanel.add(recentContainer);

        contentPanel.add(tablesPanel, java.awt.BorderLayout.CENTER);

        mainPanel.add(contentPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(mainPanel);
        mainPanel.setBounds(0, 50, 1920, 1030);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton comingButton;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JButton dashboardButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton expenditureButton;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JButton historyButton;
    private javax.swing.JPanel lowStockContainer;
    private javax.swing.JScrollPane lowStockScrollPane;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel namePanelLabel;
    private javax.swing.JButton productButton;
    private javax.swing.JPanel recentContainer;
    private javax.swing.JScrollPane recentScrollPane;
    private javax.swing.JButton settingsButton;
    private javax.swing.JPanel sidebarPanel;
    private javax.swing.JPanel tablesPanel;
    private javax.swing.JTable tblLowStock;
    private javax.swing.JTable tblRecentMovements;
    private javax.swing.JLabel userLabel;
    private javax.swing.JButton usersButton;
    private javax.swing.JButton warehouseButton;
    // End of variables declaration//GEN-END:variables
}
