/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.Panels;

/**
 *
 * @author User
 */
public class AddProductForm extends javax.swing.JFrame {

    /**
     * Creates new form AddProductForm
     */
    public AddProductForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        articleLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        unitLabel = new javax.swing.JLabel();
        categoryLabel = new javax.swing.JLabel();
        supplierNameLabel = new javax.swing.JLabel();
        purchasePriceLabel = new javax.swing.JLabel();
        sellingLabel = new javax.swing.JLabel();
        storageCellLabel = new javax.swing.JLabel();
        minStockLabel = new javax.swing.JLabel();
        articleTextField = new javax.swing.JTextField();
        namejTextField = new javax.swing.JTextField();
        categoryjComboBox = new javax.swing.JComboBox<>();
        unitjTextField = new javax.swing.JTextField();
        supplierjTextField = new javax.swing.JTextField();
        purchasePricejTextField = new javax.swing.JTextField();
        sellingPricejTextField = new javax.swing.JTextField();
        minStockjTextField = new javax.swing.JTextField();
        celljTextField = new javax.swing.JTextField();
        addjButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("AddProductForm"); // NOI18N
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(33, 37, 41));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel1.setAutoscrolls(true);
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 450));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        articleLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        articleLabel.setForeground(new java.awt.Color(255, 255, 255));
        articleLabel.setText("Артикул:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 5, 20);
        jPanel1.add(articleLabel, gridBagConstraints);

        nameLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(255, 255, 255));
        nameLabel.setText("Название:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 5, 20);
        jPanel1.add(nameLabel, gridBagConstraints);

        unitLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        unitLabel.setForeground(new java.awt.Color(255, 255, 255));
        unitLabel.setText("Количество:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 5, 20);
        jPanel1.add(unitLabel, gridBagConstraints);

        categoryLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        categoryLabel.setForeground(new java.awt.Color(255, 255, 255));
        categoryLabel.setText("Категория:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 5, 20);
        jPanel1.add(categoryLabel, gridBagConstraints);

        supplierNameLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        supplierNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        supplierNameLabel.setText("Поставщик:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 5, 20);
        jPanel1.add(supplierNameLabel, gridBagConstraints);

        purchasePriceLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        purchasePriceLabel.setForeground(new java.awt.Color(255, 255, 255));
        purchasePriceLabel.setText("Цена покупки:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 5, 20);
        jPanel1.add(purchasePriceLabel, gridBagConstraints);

        sellingLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        sellingLabel.setForeground(new java.awt.Color(255, 255, 255));
        sellingLabel.setText("Цена продажи:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 5, 20);
        jPanel1.add(sellingLabel, gridBagConstraints);

        storageCellLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        storageCellLabel.setForeground(new java.awt.Color(255, 255, 255));
        storageCellLabel.setText("Ячейка:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 5, 20);
        jPanel1.add(storageCellLabel, gridBagConstraints);

        minStockLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        minStockLabel.setForeground(new java.awt.Color(255, 255, 255));
        minStockLabel.setText("Мин. остаток:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 5, 20);
        jPanel1.add(minStockLabel, gridBagConstraints);

        articleTextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        articleTextField.setForeground(new java.awt.Color(255, 255, 255));
        articleTextField.setMinimumSize(new java.awt.Dimension(100, 30));
        articleTextField.setPreferredSize(new java.awt.Dimension(100, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 5, 20);
        jPanel1.add(articleTextField, gridBagConstraints);

        namejTextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        namejTextField.setForeground(new java.awt.Color(255, 255, 255));
        namejTextField.setMinimumSize(new java.awt.Dimension(100, 30));
        namejTextField.setPreferredSize(new java.awt.Dimension(100, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 5, 20);
        jPanel1.add(namejTextField, gridBagConstraints);

        categoryjComboBox.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        categoryjComboBox.setForeground(new java.awt.Color(255, 255, 255));
        categoryjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        categoryjComboBox.setMinimumSize(new java.awt.Dimension(100, 30));
        categoryjComboBox.setPreferredSize(new java.awt.Dimension(100, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 5, 20);
        jPanel1.add(categoryjComboBox, gridBagConstraints);

        unitjTextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        unitjTextField.setForeground(new java.awt.Color(255, 255, 255));
        unitjTextField.setMinimumSize(new java.awt.Dimension(100, 30));
        unitjTextField.setPreferredSize(new java.awt.Dimension(100, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 5, 20);
        jPanel1.add(unitjTextField, gridBagConstraints);

        supplierjTextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        supplierjTextField.setForeground(new java.awt.Color(255, 255, 255));
        supplierjTextField.setMinimumSize(new java.awt.Dimension(100, 30));
        supplierjTextField.setPreferredSize(new java.awt.Dimension(100, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 5, 20);
        jPanel1.add(supplierjTextField, gridBagConstraints);

        purchasePricejTextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        purchasePricejTextField.setForeground(new java.awt.Color(255, 255, 255));
        purchasePricejTextField.setMinimumSize(new java.awt.Dimension(100, 30));
        purchasePricejTextField.setPreferredSize(new java.awt.Dimension(100, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 5, 20);
        jPanel1.add(purchasePricejTextField, gridBagConstraints);

        sellingPricejTextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        sellingPricejTextField.setForeground(new java.awt.Color(255, 255, 255));
        sellingPricejTextField.setMinimumSize(new java.awt.Dimension(100, 30));
        sellingPricejTextField.setPreferredSize(new java.awt.Dimension(100, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 5, 20);
        jPanel1.add(sellingPricejTextField, gridBagConstraints);

        minStockjTextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        minStockjTextField.setForeground(new java.awt.Color(255, 255, 255));
        minStockjTextField.setMinimumSize(new java.awt.Dimension(100, 30));
        minStockjTextField.setPreferredSize(new java.awt.Dimension(100, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 5, 20);
        jPanel1.add(minStockjTextField, gridBagConstraints);

        celljTextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        celljTextField.setForeground(new java.awt.Color(255, 255, 255));
        celljTextField.setMinimumSize(new java.awt.Dimension(100, 30));
        celljTextField.setPreferredSize(new java.awt.Dimension(100, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 5, 20);
        jPanel1.add(celljTextField, gridBagConstraints);

        addjButton.setBackground(new java.awt.Color(52, 152, 219));
        addjButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        addjButton.setForeground(new java.awt.Color(255, 255, 255));
        addjButton.setText("Добавить");
        addjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addjButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 20, 0);
        jPanel1.add(addjButton, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addjButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_addjButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddProductForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddProductForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddProductForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddProductForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddProductForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addjButton;
    private javax.swing.JLabel articleLabel;
    private javax.swing.JTextField articleTextField;
    private javax.swing.JLabel categoryLabel;
    private javax.swing.JComboBox<String> categoryjComboBox;
    private javax.swing.JTextField celljTextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel minStockLabel;
    private javax.swing.JTextField minStockjTextField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField namejTextField;
    private javax.swing.JLabel purchasePriceLabel;
    private javax.swing.JTextField purchasePricejTextField;
    private javax.swing.JLabel sellingLabel;
    private javax.swing.JTextField sellingPricejTextField;
    private javax.swing.JLabel storageCellLabel;
    private javax.swing.JLabel supplierNameLabel;
    private javax.swing.JTextField supplierjTextField;
    private javax.swing.JLabel unitLabel;
    private javax.swing.JTextField unitjTextField;
    // End of variables declaration//GEN-END:variables
}
