/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.Panels;

/**
 *
 * @author User
 */
public class IncomePanel extends javax.swing.JPanel {

    /**
     * Creates new form IncomePanel
     */
    public IncomePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        incomeHeaderPanel = new javax.swing.JPanel();
        namePanelLabel = new javax.swing.JLabel();
        incomeDateLabel = new javax.swing.JLabel();
        incomeContentPanel = new javax.swing.JPanel();
        productNameLabel = new javax.swing.JLabel();
        nameProductComboBox = new javax.swing.JComboBox<>();
        nameWarehouseLabel = new javax.swing.JLabel();
        nameWarehouseComboBox = new javax.swing.JComboBox<>();
        quantityLabel = new javax.swing.JLabel();
        quantityTextField = new javax.swing.JTextField();
        priceLabel = new javax.swing.JLabel();
        priceTextField = new javax.swing.JTextField();
        providerLabel = new javax.swing.JLabel();
        providerTextField = new javax.swing.JTextField();
        cellLabel = new javax.swing.JLabel();
        cellTextField = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(33, 37, 41));
        setLayout(new java.awt.BorderLayout());

        incomeHeaderPanel.setBackground(new java.awt.Color(33, 37, 41));
        incomeHeaderPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        incomeHeaderPanel.setLayout(new java.awt.GridBagLayout());

        namePanelLabel.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        namePanelLabel.setForeground(new java.awt.Color(255, 255, 255));
        namePanelLabel.setText("Приход Товара");
        namePanelLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        incomeHeaderPanel.add(namePanelLabel, new java.awt.GridBagConstraints());

        incomeDateLabel.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        incomeDateLabel.setForeground(new java.awt.Color(255, 255, 255));
        incomeDateLabel.setText("время");
        incomeDateLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        incomeHeaderPanel.add(incomeDateLabel, new java.awt.GridBagConstraints());

        add(incomeHeaderPanel, java.awt.BorderLayout.PAGE_START);

        incomeContentPanel.setBackground(new java.awt.Color(33, 37, 41));
        incomeContentPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ОФОРМИТЬ ПРИХОД", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 20), new java.awt.Color(255, 255, 255))); // NOI18N
        incomeContentPanel.setPreferredSize(new java.awt.Dimension(250, 400));
        incomeContentPanel.setLayout(new java.awt.GridBagLayout());

        productNameLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        productNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        productNameLabel.setText("Товар:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 10, 5);
        incomeContentPanel.add(productNameLabel, gridBagConstraints);

        nameProductComboBox.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        nameProductComboBox.setForeground(new java.awt.Color(0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 10, 5);
        incomeContentPanel.add(nameProductComboBox, gridBagConstraints);

        nameWarehouseLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        nameWarehouseLabel.setForeground(new java.awt.Color(255, 255, 255));
        nameWarehouseLabel.setText("Склад:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 10, 5);
        incomeContentPanel.add(nameWarehouseLabel, gridBagConstraints);

        nameWarehouseComboBox.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        nameWarehouseComboBox.setForeground(new java.awt.Color(0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 10, 5);
        incomeContentPanel.add(nameWarehouseComboBox, gridBagConstraints);

        quantityLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        quantityLabel.setForeground(new java.awt.Color(255, 255, 255));
        quantityLabel.setText("Количество:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 10, 5);
        incomeContentPanel.add(quantityLabel, gridBagConstraints);

        quantityTextField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        quantityTextField.setForeground(new java.awt.Color(0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 10, 5);
        incomeContentPanel.add(quantityTextField, gridBagConstraints);

        priceLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        priceLabel.setForeground(new java.awt.Color(255, 255, 255));
        priceLabel.setText("Цена:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 10, 5);
        incomeContentPanel.add(priceLabel, gridBagConstraints);

        priceTextField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        priceTextField.setForeground(new java.awt.Color(0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 10, 5);
        incomeContentPanel.add(priceTextField, gridBagConstraints);

        providerLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        providerLabel.setForeground(new java.awt.Color(255, 255, 255));
        providerLabel.setText("Поставщик:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 10, 5);
        incomeContentPanel.add(providerLabel, gridBagConstraints);

        providerTextField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        providerTextField.setForeground(new java.awt.Color(0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 10, 5);
        incomeContentPanel.add(providerTextField, gridBagConstraints);

        cellLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cellLabel.setForeground(new java.awt.Color(255, 255, 255));
        cellLabel.setText("Ячейка:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 10, 5);
        incomeContentPanel.add(cellLabel, gridBagConstraints);

        cellTextField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cellTextField.setForeground(new java.awt.Color(0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 10, 5);
        incomeContentPanel.add(cellTextField, gridBagConstraints);

        addButton.setBackground(new java.awt.Color(40, 167, 69));
        addButton.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        addButton.setForeground(new java.awt.Color(255, 255, 255));
        addButton.setText("Оформить");
        addButton.setFocusPainted(false);
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 10, 5);
        incomeContentPanel.add(addButton, gridBagConstraints);

        add(incomeContentPanel, java.awt.BorderLayout.WEST);
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JLabel cellLabel;
    private javax.swing.JTextField cellTextField;
    private javax.swing.JPanel incomeContentPanel;
    private javax.swing.JLabel incomeDateLabel;
    private javax.swing.JPanel incomeHeaderPanel;
    private javax.swing.JLabel namePanelLabel;
    private javax.swing.JComboBox<String> nameProductComboBox;
    private javax.swing.JComboBox<String> nameWarehouseComboBox;
    private javax.swing.JLabel nameWarehouseLabel;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JTextField priceTextField;
    private javax.swing.JLabel productNameLabel;
    private javax.swing.JLabel providerLabel;
    private javax.swing.JTextField providerTextField;
    private javax.swing.JLabel quantityLabel;
    private javax.swing.JTextField quantityTextField;
    // End of variables declaration//GEN-END:variables
}
