/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.Panels;

import controllers.Controller;
import dao.UserDAO;
import model.User;

import javax.swing.*;

/**
 *
 * @author User
 */
public class UserAddForm extends javax.swing.JFrame {

    /**
     * Creates new form UserAddForm
     */
    final Controller con = new Controller();
    final UserDAO dao = new UserDAO();

    public UserAddForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        loginLable = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        roleLabel = new javax.swing.JLabel();
        loginTextField = new javax.swing.JTextField();
        passwordjTextField = new javax.swing.JTextField();
        rolejComboBox = new javax.swing.JComboBox<>();
        namejTextField = new javax.swing.JTextField();
        addjButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(33, 37, 41));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel1.setAutoscrolls(true);
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 450));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        loginLable.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        loginLable.setForeground(new java.awt.Color(255, 255, 255));
        loginLable.setText("Логин:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 5, 20);
        jPanel1.add(loginLable, gridBagConstraints);

        passwordLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(255, 255, 255));
        passwordLabel.setText("Пароль:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 5, 20);
        jPanel1.add(passwordLabel, gridBagConstraints);

        nameLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(255, 255, 255));
        nameLabel.setText("ФИО:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 5, 20);
        jPanel1.add(nameLabel, gridBagConstraints);

        roleLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        roleLabel.setForeground(new java.awt.Color(255, 255, 255));
        roleLabel.setText("Роль:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 5, 20);
        jPanel1.add(roleLabel, gridBagConstraints);

        loginTextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        loginTextField.setForeground(new java.awt.Color(0, 0, 0));
        loginTextField.setCaretColor(new java.awt.Color(0, 0, 0));
        loginTextField.setMinimumSize(new java.awt.Dimension(100, 30));
        loginTextField.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 5, 20);
        jPanel1.add(loginTextField, gridBagConstraints);

        passwordjTextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        passwordjTextField.setForeground(new java.awt.Color(0, 0, 0));
        passwordjTextField.setCaretColor(new java.awt.Color(0, 0, 0));
        passwordjTextField.setMinimumSize(new java.awt.Dimension(100, 30));
        passwordjTextField.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 5, 20);
        jPanel1.add(passwordjTextField, gridBagConstraints);

        rolejComboBox.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rolejComboBox.setForeground(new java.awt.Color(0, 0, 0));
        rolejComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Администратор\t", "Пользователь" }));
        rolejComboBox.setMinimumSize(new java.awt.Dimension(100, 30));
        rolejComboBox.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 5, 20);
        jPanel1.add(rolejComboBox, gridBagConstraints);

        namejTextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        namejTextField.setForeground(new java.awt.Color(0, 0, 0));
        namejTextField.setCaretColor(new java.awt.Color(0, 0, 0));
        namejTextField.setMinimumSize(new java.awt.Dimension(100, 30));
        namejTextField.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 5, 20);
        jPanel1.add(namejTextField, gridBagConstraints);

        addjButton.setBackground(new java.awt.Color(52, 152, 219));
        addjButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        addjButton.setForeground(new java.awt.Color(255, 255, 255));
        addjButton.setText("Добавить");
        addjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addjButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 20, 0);
        jPanel1.add(addjButton, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addjButtonActionPerformed
        if (con.addUserCheckAccept(loginTextField.getText(), passwordjTextField.getText(), namejTextField.getText(), (String) rolejComboBox.getSelectedItem()))
        {
            JOptionPane.showMessageDialog(this, "Заполните все поля", "Внимание", JOptionPane.WARNING_MESSAGE);
            return;
        }
        User u = con.addNewUser(loginTextField.getText(), passwordjTextField.getText(), namejTextField.getText(), (String) rolejComboBox.getSelectedItem());
        if (dao.addUser(u)) {
            JOptionPane.showMessageDialog(this, "Товар был успешно добавлен", "Успех", JOptionPane.INFORMATION_MESSAGE);
            this.setVisible(false);
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Произошла непредвиденная ошибка, пожалуйста немедленно обратитесь к разработчику", "ОШИБКА", JOptionPane.ERROR_MESSAGE);
            this.setVisible(false);
        }
    }//GEN-LAST:event_addjButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserAddForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserAddForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserAddForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserAddForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserAddForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addjButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel loginLable;
    private javax.swing.JTextField loginTextField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField namejTextField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField passwordjTextField;
    private javax.swing.JLabel roleLabel;
    private javax.swing.JComboBox<String> rolejComboBox;
    // End of variables declaration//GEN-END:variables
}
