/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.Panels;

import dao.UserDAO;
import model.Product;
import model.User;

import javax.swing.table.DefaultTableModel;
import java.util.List;

/**
 *
 * @author User
 */
public class usersPanel extends javax.swing.JPanel {
    UserDAO userDAO = new UserDAO();

    /**
     * Creates new form usersPanel
     */
    public usersPanel() {
        initComponents();
        loadUserData();
    }

    private void loadUserData() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        try {
            List<User> users = userDAO.getAllUsers();

            if (users.isEmpty()) {
                model.addRow(new Object[]{"—", "Ошибка загрузки пользователей", "—", "—", "—", "—"});
            } else {
                for (User u : users) {
                    model.addRow(new Object[]{
                            u.getId(),
                            u.getLogin(),
                            u.getPassword(),
                            u.getFullName(),
                            u.getRole(),
                            u.getIsBlocked(),
                            u.getLastLogin(),
                            u.isMustChangePassword(),
                            u.getCreatedAt()
                    });
                }
            }
            System.out.println("✅ Загружено пользователей: " + users.size());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usersHeaderPanel = new javax.swing.JPanel();
        namePanelLabel = new javax.swing.JLabel();
        usersDateLabel = new javax.swing.JLabel();
        usersContentPanel = new javax.swing.JPanel();
        usersTabelPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        usersHeaderPanel.setBackground(new java.awt.Color(33, 37, 41));
        usersHeaderPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        usersHeaderPanel.setLayout(new java.awt.GridBagLayout());

        namePanelLabel.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        namePanelLabel.setForeground(new java.awt.Color(255, 255, 255));
        namePanelLabel.setText("Управление пользователями");
        namePanelLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        usersHeaderPanel.add(namePanelLabel, new java.awt.GridBagConstraints());

        usersDateLabel.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        usersDateLabel.setForeground(new java.awt.Color(255, 255, 255));
        usersDateLabel.setText("время");
        usersDateLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        usersHeaderPanel.add(usersDateLabel, new java.awt.GridBagConstraints());

        add(usersHeaderPanel, java.awt.BorderLayout.PAGE_START);

        usersContentPanel.setLayout(new java.awt.BorderLayout());

        usersTabelPanel.setBackground(new java.awt.Color(33, 37, 41));
        usersTabelPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ПОЛЬЗОВАТЕЛИ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 20), new java.awt.Color(255, 255, 255))); // NOI18N
        usersTabelPanel.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        usersTabelPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        usersContentPanel.add(usersTabelPanel, java.awt.BorderLayout.CENTER);

        add(usersContentPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel namePanelLabel;
    private javax.swing.JPanel usersContentPanel;
    private javax.swing.JLabel usersDateLabel;
    private javax.swing.JPanel usersHeaderPanel;
    private javax.swing.JPanel usersTabelPanel;
    // End of variables declaration//GEN-END:variables
}
