/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.Panels;

import dao.WarehouseDAO;
import model.Warehouse;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;

/**
 *
 * @author User
 */
public class WarehousesPanel extends javax.swing.JPanel {

    /**
     * Creates new form WarehousesPanel
     */
    private WarehouseDAO warehouseDAO = new WarehouseDAO();
    public WarehousesPanel() {
        initComponents();
        loadData();
    }

    public void loadData()
    {
        loadWarehouseData();
    }


    private void loadWarehouseData() {
        DefaultTableModel model = (DefaultTableModel) tblWarehouse.getModel();
        model.setRowCount(0);

        try {
            List<Warehouse> warehouse = warehouseDAO.getAllWarehouses();

            if (warehouse.isEmpty()) {
                model.addRow(new Object[]{"—", "Нет товаров", "—", "—", "—", "—"});
            } else {
                for (Warehouse w : warehouse) {
                    model.addRow(new Object[]{
                            w.getId(),
                            w.getName(),
                            w.getAddress()
                    });
                }
            }
            System.out.println("✅ Загружено товаров: " + warehouse.size());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        warehouseHeaderPanel = new javax.swing.JPanel();
        namePanelLabel = new javax.swing.JLabel();
        warehouseDateLabel = new javax.swing.JLabel();
        buttonPanel = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();
        tablePanel = new javax.swing.JPanel();
        tableScrollPane = new javax.swing.JScrollPane();
        tblWarehouse = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        warehouseHeaderPanel.setBackground(new java.awt.Color(33, 37, 41));
        warehouseHeaderPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        warehouseHeaderPanel.setLayout(new java.awt.GridBagLayout());

        namePanelLabel.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        namePanelLabel.setForeground(new java.awt.Color(255, 255, 255));
        namePanelLabel.setText("Управление складами");
        namePanelLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        warehouseHeaderPanel.add(namePanelLabel, new java.awt.GridBagConstraints());

        warehouseDateLabel.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        warehouseDateLabel.setForeground(new java.awt.Color(255, 255, 255));
        warehouseDateLabel.setText("время");
        warehouseDateLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        warehouseHeaderPanel.add(warehouseDateLabel, new java.awt.GridBagConstraints());

        add(warehouseHeaderPanel, java.awt.BorderLayout.PAGE_START);

        buttonPanel.setBackground(new java.awt.Color(33, 37, 41));
        buttonPanel.setMaximumSize(new java.awt.Dimension(900, 35));
        buttonPanel.setMinimumSize(new java.awt.Dimension(900, 35));
        buttonPanel.setPreferredSize(new java.awt.Dimension(900, 35));

        addButton.setBackground(new java.awt.Color(40, 167, 69));
        addButton.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        addButton.setForeground(new java.awt.Color(255, 255, 255));
        addButton.setText("Добавить");
        addButton.setFocusPainted(false);
        addButton.setPreferredSize(new java.awt.Dimension(130, 35));
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(addButton);

        editButton.setBackground(new java.awt.Color(255, 193, 7));
        editButton.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        editButton.setForeground(new java.awt.Color(255, 255, 255));
        editButton.setText("Редактировать");
        editButton.setFocusPainted(false);
        editButton.setMaximumSize(new java.awt.Dimension(190, 29));
        editButton.setPreferredSize(new java.awt.Dimension(170, 35));
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(editButton);

        deleteButton.setBackground(new java.awt.Color(220, 53, 69));
        deleteButton.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        deleteButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteButton.setText("Удалить");
        deleteButton.setFocusPainted(false);
        deleteButton.setPreferredSize(new java.awt.Dimension(130, 35));
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(deleteButton);

        refreshButton.setBackground(new java.awt.Color(255, 153, 0));
        refreshButton.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        refreshButton.setForeground(new java.awt.Color(255, 255, 255));
        refreshButton.setText("Обновить");
        refreshButton.setFocusPainted(false);
        refreshButton.setPreferredSize(new java.awt.Dimension(130, 35));
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(refreshButton);

        add(buttonPanel, java.awt.BorderLayout.CENTER);

        tablePanel.setBackground(new java.awt.Color(33, 37, 41));
        tablePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "СКЛАДЫ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 20), new java.awt.Color(255, 255, 255))); // NOI18N
        tablePanel.setPreferredSize(new java.awt.Dimension(900, 900));
        tablePanel.setLayout(new java.awt.BorderLayout());

        tableScrollPane.setBackground(new java.awt.Color(255, 255, 255));
        tableScrollPane.setPreferredSize(new java.awt.Dimension(900, 700));

        tblWarehouse.setBackground(new java.awt.Color(255, 255, 255));
        tblWarehouse.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tblWarehouse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblWarehouse.setRowHeight(30);
        tableScrollPane.setViewportView(tblWarehouse);

        tablePanel.add(tableScrollPane, java.awt.BorderLayout.CENTER);

        add(tablePanel, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        AddWarehouseForm addForm = new AddWarehouseForm();
        addForm.setVisible(true);
    }//GEN-LAST:event_addButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        loadData();
        JOptionPane.showMessageDialog(this, "Данные успешно обнавлены", "Успех", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_refreshButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel namePanelLabel;
    private javax.swing.JButton refreshButton;
    private javax.swing.JPanel tablePanel;
    private javax.swing.JScrollPane tableScrollPane;
    private javax.swing.JTable tblWarehouse;
    private javax.swing.JLabel warehouseDateLabel;
    private javax.swing.JPanel warehouseHeaderPanel;
    // End of variables declaration//GEN-END:variables
}
